# GitLab CI Configuration file

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

stages:
  - build
  - publish

build-job:
  stage: build
  image: registry.gitlab.com/radixhomework/docker-images/maven:latest
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  only:
    - merge_requests
    - master
    - develop
  script:
    - mvn install
    - mvn verify sonar:sonar
   #- 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file path/to/file.txt "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/0.0.1/file.txt"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "tlm-windows/target/Time Lapse Maker.exe" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/time-lapse-maker/snapshot/Time Lapse Maker.exe"'

publish-package:
  stage: publish
  image: curlimages/curl:latest
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "tlm-windows/target/Time Lapse Maker.exe" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/time-lapse-maker/snapshot/Time Lapse Maker.exe"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "tlm-macos/target/Time Lapse Maker.app" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/time-lapse-maker/snapshot/Time Lapse Maker.app"'
