# GitLab CI Configuration file

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  PKG_NAME: "time-lapse-maker"
  OUT_PREF: "Time_Lapse_Maker"

stages:
  - build-snapshot
  - build-tag

build-snapshot:
  stage: build-snapshot
  image: registry.gitlab.com/radixhomework/docker-images/maven:latest
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  only:
    - master
    - develop
  script:
    - mvn install
    - mvn verify sonar:sonar
    - mvn deploy -s ci_settings.xml

build-tag:
  stage: build-tag
  only:
    - tags
  image: registry.gitlab.com/radixhomework/docker-images/maven:latest
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn install
    - OUT_VERS=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - >
      curl
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file "tlm-windows/target/${OUT_PREF}-windows.zip"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PKG_NAME}/${OUT_VERS}/${OUT_PREF}-windows.zip"
    - >
      curl
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file "tlm-macos/target/${OUT_PREF}-macos.zip"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PKG_NAME}/${OUT_VERS}/${OUT_PREF}-macos.zip"
    - >
      curl
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file "tlm-linux/target/${OUT_PREF}-linux.tar.gz"
      "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PKG_NAME}/${OUT_VERS}/${OUT_PREF}-linux.tar.gz"
